name: End-to-End tests with TestCafe action  

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DISPLAY: ":99.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install WM
        run: sudo apt install fluxbox
      
      - name: Run X11
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          fluxbox &
          
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx testcafe electron:. ./tests/test.js -p '${DATE}_${TIME}_${TEST_ID}.png' -S -s screenshots
      
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: screenshots